name: file_icon
description: File icons for different file types, auto detected by file name.
version: 1.0.0
author: Rongjian Zhang <pd4d10@gmail.com>
homepage: https://github.com/pd4d10/file-icon

environment:
  sdk: '>=2.19.0-273.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Seti
      fonts:
        - asset: fonts/seti.ttf
